import type { CheckDefinition, CheckPersona, CheckSkill } from '../types'

const STUB_PERSONA: CheckPersona = {
  name: 'Tier 3',
  role: 'Not implemented',
  systemPrompt: '',
  expertise: [] as const,
  citationGuidance: '',
}

const STUB_SKILL: CheckSkill = {
  async execute() {
    throw new Error('Tier 3 checks do not execute — use definition metadata only')
  },
}

function def(
  id: string,
  category: CheckDefinition['category'],
  name: string,
  description: string,
  whyItMatters: string,
  dataSource: string,
  dataMode: CheckDefinition['dataMode'] = 'programmatic',
  relatedQuestions: string[] = [],
): CheckDefinition {
  return {
    id,
    category,
    name,
    description,
    whyItMatters,
    dataMode,
    dataSource,
    tier: 3,
    activationRules: [],
    relatedQuestions,
  }
}

export const TIER3_DEFINITIONS: CheckDefinition[] = [
  // Physical structure
  def(
    'building-permits',
    'physical-structure',
    'Building Permit History',
    'Review historical building permits for additions, renovations, and structural changes',
    'Unpermitted work can require costly remediation and affect insurance coverage',
    'Municipal building permit records',
    'programmatic',
    ['Is there any existing damage or issues?'],
  ),
  def(
    'water-quality',
    'physical-structure',
    'Water Quality',
    'Assess drinking water quality, especially for well water properties',
    'Water quality issues can be costly to remediate and affect health',
    'Water quality test results',
    'manual',
    ['Is this property safe?'],
  ),
  def(
    'roof-condition',
    'physical-structure',
    'Roof Condition & Life Expectancy',
    'Assess roof age, material, and remaining service life',
    'Roof replacement is a major expense; knowing condition helps budget',
    'Home inspection report',
    'manual',
    ['Is there any existing damage or issues?', 'Am I going to get hit with surprise costs?'],
  ),
  def(
    'foundation-inspection',
    'physical-structure',
    'Foundation & Structural',
    'Evaluate foundation condition, cracks, and structural integrity',
    'Foundation issues are among the most expensive to remediate',
    'Structural engineering report, home inspection',
    'manual',
    ['Is there any existing damage or issues?', 'Is this property safe?'],
  ),
  def(
    'electrical-systems',
    'physical-structure',
    'Electrical Systems',
    'Check panel capacity, wiring age, and compliance with current codes',
    'Older electrical systems may need upgrades for insurance or safety',
    'Home inspection report',
    'manual',
    ['Is this property safe?', 'Am I going to get hit with surprise costs?'],
  ),
  def(
    'plumbing-systems',
    'physical-structure',
    'Plumbing & Sewer',
    'Assess plumbing condition, pipe materials, and sewer line',
    'Sewer line replacement can cost thousands; poly B and lead piping are concerns',
    'Home inspection, sewer scope',
    'manual',
    ['Is there any existing damage or issues?', 'Am I going to get hit with surprise costs?'],
  ),
  def(
    'hvac-condition',
    'physical-structure',
    'HVAC & Heating',
    'Evaluate furnace, AC, heat pump age and efficiency',
    'HVAC replacement is a significant capital expense',
    'Home inspection report',
    'manual',
    ['Am I going to get hit with surprise costs?'],
  ),
  def(
    'asbestos-assessment',
    'physical-structure',
    'Asbestos & Hazardous Materials',
    'Identify potential asbestos in insulation, tiles, or drywall',
    'Asbestos remediation adds cost and complexity to renovations',
    'Asbestos survey, home inspection',
    'manual',
    ['Is this property safe?', 'Is there any existing damage or issues?'],
  ),
  def(
    'mould-assessment',
    'physical-structure',
    'Mould & Moisture',
    'Check for moisture intrusion, mould, or water damage',
    'Mould can affect health and requires remediation',
    'Home inspection, moisture testing',
    'manual',
    ['Is this property safe?', 'Is there any existing damage or issues?'],
  ),
  def(
    'pest-inspection',
    'physical-structure',
    'Pest & Wood-Destroying Organisms',
    'Inspect for termites, carpenter ants, rodents, or other pests',
    'Pest damage can compromise structure and be costly to repair',
    'Pest inspection report',
    'manual',
    ['Is there any existing damage or issues?'],
  ),
  def(
    'septic-system',
    'physical-structure',
    'Septic System',
    'Assess septic tank and drainfield condition and compliance',
    'Septic failure requires costly replacement; compliance may be required for sale',
    'Septic inspection, municipal records',
    'manual',
    ['Is there any existing damage or issues?', 'Am I going to get hit with surprise costs?'],
  ),
  def(
    'well-capacity',
    'physical-structure',
    'Well Capacity & Water Supply',
    'Test well output and water availability',
    'Low-yield wells can limit landscaping, pools, or secondary dwellings',
    'Well flow test',
    'manual',
    ['Is this property safe?'],
  ),
  // Land & natural hazards
  def(
    'flood-zone',
    'land-natural-hazards',
    'Flood Zone Mapping',
    'Determine if property is in a designated flood zone or floodplain',
    'Flood zones affect insurance costs, development restrictions, and resale value',
    'BC Flood Hazard Maps, Municipal flood maps',
    'programmatic',
    ['Is this property safe?'],
  ),
  def(
    'soil-stability',
    'land-natural-hazards',
    'Soil & Geotechnical',
    'Assess soil conditions, bearing capacity, and slope stability',
    'Poor soil can cause foundation issues, drainage problems, and limit building options',
    'Geotechnical engineering report',
    'manual',
    ['Is this property safe?', 'Is there any existing damage or issues?'],
  ),
  def(
    'tsunami-hazard',
    'land-natural-hazards',
    'Tsunami Hazard',
    'Evaluate coastal properties for tsunami inundation risk',
    'Coastal BC properties may be in tsunami hazard zones',
    'Emergency Management BC, municipal mapping',
    'programmatic',
    ['Is this property safe?'],
  ),
  def(
    'slope-stability',
    'land-natural-hazards',
    'Slope & Landslide Risk',
    'Assess slope stability and landslide susceptibility',
    'Slope failures can damage property and affect insurance',
    'Geotechnical report, municipal hazard mapping',
    'manual',
    ['Is this property safe?'],
  ),
  // Land use & zoning
  def(
    'heritage-designation',
    'land-use-zoning',
    'Heritage Designation',
    'Check if the property is on a heritage register or has heritage protection',
    'Heritage designation can restrict renovations and demolition while potentially offering grants',
    'Municipal heritage register',
    'programmatic',
    ['What am I allowed to do with this property?'],
  ),
  def(
    'agricultural-land-reserve',
    'land-use-zoning',
    'Agricultural Land Reserve',
    'Determine if property is in the ALR',
    'ALR designation severely restricts land use and development',
    'BC ALR maps, LTSA',
    'programmatic',
    ['What am I allowed to do with this property?'],
  ),
  def(
    'development-permit-area',
    'land-use-zoning',
    'Development Permit Area',
    'Check if property is in a DPA with design guidelines',
    'DPA may require approval for exterior changes or new construction',
    'Municipal OCP, zoning maps',
    'programmatic',
    ['What am I allowed to do with this property?'],
  ),
  // Neighbourhood
  def(
    'neighbourhood-safety',
    'neighbourhood-context',
    'Neighbourhood Safety Statistics',
    'Crime statistics, safety ratings, and community safety initiatives',
    'Safety affects quality of life, insurance premiums, and property values',
    'VPD GeoDash, ICBC crash data',
    'programmatic',
    ["What's the neighbourhood really like?"],
  ),
  def(
    'schools-proximity',
    'neighbourhood-context',
    'Schools & Education',
    'Nearby schools, catchment areas, and school quality ratings',
    'School quality directly impacts family livability and property values',
    'BC Ministry of Education, Fraser Institute',
    'programmatic',
    ["What's the neighbourhood really like?"],
  ),
  def(
    'transit-access',
    'neighbourhood-context',
    'Transit & Transportation',
    'Proximity to transit, bike routes, and transportation options',
    'Transit access affects commute times and property desirability',
    'TransLink, BC Transit, municipal plans',
    'programmatic',
    ["What's the neighbourhood really like?"],
  ),
  def(
    'development-applications',
    'neighbourhood-context',
    'Nearby Development Applications',
    'Active rezoning, development permits, and construction projects in the vicinity',
    'Nearby development can affect views, traffic, noise, and property values',
    'Municipal development tracker',
    'programmatic',
    ['What could change in the future?', "What's the neighbourhood really like?"],
  ),
  def(
    'noise-exposure',
    'neighbourhood-context',
    'Noise & Sound Exposure',
    'Assess noise from traffic, airports, industry, or construction',
    'Noise can affect livability and may have disclosure requirements',
    'Municipal noise studies, proximity mapping',
    'programmatic',
    ["What's the neighbourhood really like?"],
  ),
  def(
    'walkability',
    'neighbourhood-context',
    'Walkability & Amenities',
    'Walk scores, nearby amenities, parks, and services',
    'Walkability affects lifestyle and resale appeal',
    'Walk Score, Google Maps',
    'programmatic',
    ["What's the neighbourhood really like?"],
  ),
  def(
    'future-planning',
    'neighbourhood-context',
    'Future Planning & Rezoning',
    'Planned infrastructure, transit expansion, or area rezoning',
    'Future plans can significantly affect property value and character',
    'Municipal OCP, provincial plans',
    'programmatic',
    ['What could change in the future?'],
  ),
  // Regulatory compliance
  def(
    'strata-review',
    'regulatory-compliance',
    'Strata Documentation Review',
    'Review strata minutes, bylaws, depreciation report, and financial statements',
    'Strata issues (special levies, building envelope, governance) are leading sources of buyer surprise',
    'Strata corporation documents (Form B, minutes, depreciation report)',
    'manual',
    ['Am I going to get hit with surprise costs?', 'Are there any legal complications?'],
  ),
  def(
    'rental-restrictions',
    'regulatory-compliance',
    'Rental & Occupancy Restrictions',
    'Strata rental bylaws, age restrictions, pet policies',
    'Restrictions may limit your intended use or resale market',
    'Strata bylaws, Form B',
    'manual',
    ['Can I rent this out or Airbnb it?'],
  ),
  def(
    'short-term-rental-rules',
    'regulatory-compliance',
    'Short-Term Rental Rules',
    'Municipal STR bylaws, licensing requirements, strata restrictions',
    'STR rules vary by municipality; non-compliance has consequences',
    'Municipal bylaws, strata documents',
    'programmatic',
    ['Can I rent this out or Airbnb it?'],
  ),
  def(
    'building-code-compliance',
    'regulatory-compliance',
    'Building Code Compliance',
    'Verify additions and renovations meet code requirements',
    'Non-compliant work can require costly remediation',
    'Municipal records, home inspection',
    'manual',
    ['Are there any legal complications?', 'Is there any existing damage or issues?'],
  ),
  def(
    'suite-legalization',
    'regulatory-compliance',
    'Secondary Suite Legalization',
    'Check if existing suite is permitted and complies with bylaws',
    'Illegal suites can require costly legalization or removal',
    'Municipal permits, zoning',
    'programmatic',
    ['Can I rent this out or Airbnb it?', 'What am I allowed to do with this property?'],
  ),
  // Financial
  def(
    'insurance-assessment',
    'financial',
    'Insurance Assessment',
    'Estimate insurance costs and identify coverage concerns',
    'Insurance costs can be significant; some properties are difficult to insure',
    'Insurance broker estimates, IBC data',
    'programmatic',
    ['Am I going to get hit with surprise costs?'],
  ),
  def(
    'strata-fees',
    'financial',
    'Strata Fees & Special Levies',
    'Current strata fees, history of increases, pending special levies',
    'Special levies can add thousands; fee trends indicate financial health',
    'Strata financial statements, Form B',
    'manual',
    ['Am I going to get hit with surprise costs?'],
  ),
  def(
    'property-taxes',
    'financial',
    'Property Tax Assessment',
    'Current and historical property taxes, assessment value',
    'Taxes affect affordability; assessment disputes may be possible',
    'BC Assessment, municipal tax records',
    'programmatic',
    ['Am I going to get hit with surprise costs?'],
  ),
  def(
    'utility-costs',
    'financial',
    'Utility Costs',
    'Typical hydro, gas, water, and sewer costs for the property',
    'High utility costs affect ongoing affordability',
    'BC Hydro, FortisBC, municipal utilities',
    'programmatic',
    ['Am I going to get hit with surprise costs?'],
  ),
  // Transaction risk
  def(
    'disclosure-review',
    'transaction-risk',
    'Disclosure Statement Review',
    'Review seller disclosures for gaps or red flags',
    'Incomplete disclosure can create legal exposure post-sale',
    'Disclosure documents, realtor',
    'manual',
    ['Are there any legal complications?'],
  ),
  def(
    'contract-terms',
    'transaction-risk',
    'Contract Terms & Conditions',
    'Review subject clauses, deposit terms, and special conditions',
    'Contract terms affect your exit options and risk',
    'Purchase agreement',
    'manual',
    ['Are there any legal complications?'],
  ),
  def(
    'title-review',
    'transaction-risk',
    'Title Search & Encumbrances',
    'Full title review beyond basic search — restrictive covenants, rights of way',
    'Encumbrances can affect use and value',
    'LTSA title search',
    'manual',
    ['Do I actually own what I think I\'m buying?', 'Are there any legal complications?'],
  ),
  def(
    'boundary-survey',
    'transaction-risk',
    'Boundary Survey',
    'Verify property boundaries and identify encroachments',
    'Boundary disputes and encroachments can be costly to resolve',
    'Survey plan, RPR',
    'manual',
    ['Do I actually own what I think I\'m buying?'],
  ),
  // Environmental (beyond property-history)
  def(
    'underground-tanks',
    'environmental-legacy',
    'Underground Storage Tanks',
    'History of fuel or chemical storage tanks on the property',
    'USTs can leak and require costly remediation',
    'Municipal records, site assessment',
    'manual',
    ['What happened on this land before?'],
  ),
  def(
    'contaminated-sites',
    'environmental-legacy',
    'Contaminated Sites Registry',
    'Detailed BC Site Registry search and adjacent site review',
    'Proximity to contaminated sites can affect value and financing',
    'BC Contaminated Sites Registry',
    'programmatic',
    ['What happened on this land before?'],
  ),
  def(
    'wetland-designation',
    'environmental-legacy',
    'Wetland & Environmental Designation',
    'Check for wetland, riparian, or environmental area designation',
    'Environmental designations can restrict development',
    'Municipal maps, provincial databases',
    'programmatic',
    ['What am I allowed to do with this property?'],
  ),
]

export { STUB_PERSONA, STUB_SKILL }
